### ISSUE TITLE
How to send Mig-21 for India as its listed in Russian air platforms?

### ISSUE THREAD

**Issue by dev-dis** [open-dis/Enumerations#4]
Hi,

You people have done a commendable job and made people lives easier. 

I am writing here because I couldn't find way to clarify ambiguity about usage of these enumerations. I am working on to integrate Open-DIS library in my project and want to transmit an Indian Mig-21 but couldn't find way to send it as its listed in Russian Air Platforms list. Kindly guide me how to achieve this while maintaining SISO enumerations compliance and also if I send country code 99 for India in place of 222 for Russia then third party DIS compliant applications using SISO enumerations would not recognize it. 

Thanks in advance.

Regards,
Dev

**Comment by leif81** [comment]
@dev-dis here's what the 1278.1-2012 standard says about the country code field within the Entity Type record:

> Country. This field shall specify the country to which the design of the entity or its design
specification is attributed. This field shall be represented by a 16-bit enumeration (see [UID 29]).

This is likely why the Mig-21 you're referring to has country code of 222 (Russia).

Note how this differs from how country code field within Aggregate Type record is defined:

> Country. This field shall specify the country with which the aggregate is associated. This field shall
be represented by a 16-bit enumeration (see [UID 29]). If the aggregate is not associated with any
country, then the country field shall contain the number zero.

**Comment by dev-dis** [comment]
Hi Leif,

Thanks for the masterly guidance. 

What I understood is that in order to achieve association of the entity like Mig-21 for India in my case, I have to send Aggregate State PDU, am I right? One thing I would like to mention, I have multiple entities to transmit from my application with their country association and if an entity left aggregate then how can I send Entity State PDU?

Once again really thankful for your precious time and guidance.

Regards,
Dev

**Comment by dev-dis** [comment]
Hi Leif,

One thing I want to share is that as F-16 is made by General Dynamics which is listed in US platforms with subcategories F-16A, F-16B, F-16C etc. is also listed in Pakistan Plaforms as per SISO-REF-010-2022 is given below: 

> 1.2.225.1 .........................Fighter/Air Defense
> 1.2.225.1.3                               General Dynamics F-16 Fighting Falcon
> 1.2.225.1.3.1                                        F-16A
> 1.2.225.1.3.2                                        F-16B
> 1.2.225.1.3.3                                        F-16C

> 1.2.165.1 .........................Fighter/Air Defense
> 1.2.165.1.1                               F-16 (variation of 1.2.225.1.3)
> 1.2.165.1.1.1                                     F-16A
> 1.2.165.1.1.2                                     F-16B
> 1.2.165.1.1.3                                     F-16C

Where 225 is country code of US and 165 is country code of Pakistan.

I think we have to create enumerations on our own if we want to send country association. For example, if we want to send Rafale for India then we have to create Rafale enumeration for India same as F-16 enumeration created by SISO for Pakistan. I know this would create a new reference and we have to include these enumerations if we want to interoperate with third party application unless we add these enumerations in SISO reference, but this would resolve entity association. What do you say about it?

I am looking forward to hear from you soon.  

Regards,
Dev

**Comment by leif81** [comment]
@dev-dis Yes your approach should work, and is likely the simplest approach, so long as each party involved agrees to use the same enumerations.

**Comment by dev-dis** [comment]
> @dev-dis Yes your approach should work, and is likely the simplest approach, so long as each party involved agrees to use the same enumerations.

Thanks Leif for your guidance and time.
