### ISSUE TITLE
Remove JAXB dependency

### ISSUE THREAD

**Issue by leif81** [open-dis/Enumerations#6]
I don't know why the `pom.xml` still has a JAXB dependency in it. 

This can probably be safely removed but will require looking into.

~~~
<dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.1</version>
</dependency>
~~~

**Comment by brutzman** [comment]
I believe this is needed.  I will take it for action and report back.

**Comment by leif81** [comment]
@brutzman I believe I was wrong about JAXB, it appears it's still required. It's being used here to generate helper classes (https://github.com/open-dis/dis-enumerations/tree/master/src/main/java/edu/nps/moves/siso/jaxb) that are used during runtime by the `EBVReader` class to parse the SISO XML input file.
