### ISSUE TITLE
Replace build.xml with Maven exec:java command

### ISSUE THREAD

**Issue by leif81** [open-dis/Enumerations#7]
Currently this project compiles with Maven but the tool is then run with an Ant `build.xml`. To simplify the developer toolset required suggest rewriting the build.xml as a Maven execution task.

See how xmlpg is run. https://github.com/open-dis/xmlpg/blob/master/runXmlpg.sh

**Comment by brutzman** [comment]
I will continue building and developing opendis-java7 using Ant.  Parallel development paths for Maven are welcome.

**Comment by leif81** [comment]
Don one day you may still come to the dark (or is it light side)!
Having Maven do the code compilation, cleaning, unit testing, javadoc for free was a relief for me after having done the same in Ant for years.

**Comment by brutzman** [comment]
You are welcome to mavenize any of the legacy projects as you see fit.

Please note that latest enumerations are updated (after each release, currently v31) and integrated/built and then published in
- https://github.com/open-dis/opendis7-source-generator
- https://github.com/open-dis/opendis7-java
- https://savage.nps.edu/opendis7-java
